// src/inventory.js
// Pure inventory-quantity helpers. Kept in their own file rather than
// items.js — items.js is auto-generated by sync-obsidian.js and gets
// fully overwritten on every `npm run sync`; anything hand-written there
// would be silently wiped the next time content syncs.
//
// Inventory data model: characters.<id>.inventory is a map of
// { [itemId]: quantity } (e.g. { stimpak: 3, homemade_pistol: 1 }).
// Characters created before stacking existed still have the old shape in
// Firestore — a flat array of item ID strings, one entry per copy (e.g.
// ["stimpak", "stimpak", "stimpak"]). normalizeInventory() tolerates
// both and always returns the map shape. Every function below that
// writes inventory back writes the map shape wholesale (same pattern the
// old array-push code already used — replace the whole field, not a
// per-item dot-path), so a legacy character's inventory silently
// upgrades to the stacked format the first time anything touches it.

export function normalizeInventory(raw) {
  if (!raw) return {};
  if (Array.isArray(raw)) {
    const map = {};
    raw.forEach(itemId => { map[itemId] = (map[itemId] || 0) + 1; });
    return map;
  }
  return { ...raw };
}

export function getInventoryQuantity(raw, itemId) {
  return normalizeInventory(raw)[itemId] || 0;
}

export function addToInventory(raw, itemId, qty = 1) {
  const map = normalizeInventory(raw);
  map[itemId] = (map[itemId] || 0) + qty;
  return map;
}

// Floors at 0 and drops the key entirely rather than leaving a "x0" entry.
export function removeFromInventory(raw, itemId, qty = 1) {
  const map = normalizeInventory(raw);
  const remaining = (map[itemId] || 0) - qty;
  if (remaining > 0) map[itemId] = remaining;
  else delete map[itemId];
  return map;
}
